### ISSUE TITLE
PyOpenGL-accelerate install issue

### ISSUE THREAD

**Issue by hmishfaq** [rlberry-py/rlberry#46] opened 2021-03-15 18:13 UTC
I am trying to do pip install -e .[full] and get the following error. Have no idea how to resolve it. Any idea how I can solve this?

`  Stored in directory: /Users/hmishfaq/Library/Caches/pip/wheels/9f/18/84/8f69f8b08169c7bae2dde6bd7daf0c19fca8c8e500ee620a28
  Building wheel for PyOpenGL-accelerate (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/hmishfaq/miniconda3/envs/rlberry/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/setup.py'"'"'; __file__='"'"'/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-wheel-s6cu0h__
       cwd: /private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/OpenGL_accelerate
  copying OpenGL_accelerate/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/OpenGL_accelerate
  running build_ext
  building 'OpenGL_accelerate.wrapper' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/hmishfaq/miniconda3/envs/rlberry/include -arch x86_64 -I/Users/hmishfaq/miniconda3/envs/rlberry/include -arch x86_64 -I/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/.. -I/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/src -I/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15 -I/Users/hmishfaq/miniconda3/envs/rlberry/include/python3.7m -c src/wrapper.c -o build/temp.macosx-10.9-x86_64-3.7/src/wrapper.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for PyOpenGL-accelerate
  Running setup.py clean for PyOpenGL-accelerate
Successfully built pyperclip
Failed to build PyOpenGL-accelerate
Installing collected packages: zipp, urllib3, typing-extensions, pyasn1, idna, chardet, wcwidth, rsa, requests, pyperclip, pyasn1-modules, pbr, oauthlib, numpy, MarkupSafe, importlib-metadata, greenlet, colorama, cachetools, attrs, stevedore, sqlalchemy, requests-oauthlib, PyYAML, python-editor, PrettyTable, Mako, google-auth, cmd2, werkzeug, tqdm, tensorboard-plugin-wit, protobuf, packaging, markdown, llvmlite, grpcio, google-auth-oauthlib, EasyProcess, colorlog, cmaes, cliff, alembic, absl-py, torch, tensorboard, rlberry, pyvirtualdisplay, PyOpenGL-accelerate, PyOpenGL, optuna, numba, ffmpeg-python
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
  Attempting uninstall: rlberry
    Found existing installation: rlberry 0.1
    Uninstalling rlberry-0.1:
      Successfully uninstalled rlberry-0.1
  Running setup.py develop for rlberry
    Running setup.py install for PyOpenGL-accelerate ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/hmishfaq/miniconda3/envs/rlberry/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/setup.py'"'"'; __file__='"'"'/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-record-6eze1xi4/install-record.txt --single-version-externally-managed --compile --install-headers /Users/hmishfaq/miniconda3/envs/rlberry/include/python3.7m/PyOpenGL-accelerate
         cwd: /private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/OpenGL_accelerate
    copying OpenGL_accelerate/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/OpenGL_accelerate
    running build_ext
    building 'OpenGL_accelerate.wrapper' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/hmishfaq/miniconda3/envs/rlberry/include -arch x86_64 -I/Users/hmishfaq/miniconda3/envs/rlberry/include -arch x86_64 -I/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/.. -I/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/src -I/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15 -I/Users/hmishfaq/miniconda3/envs/rlberry/include/python3.7m -c src/wrapper.c -o build/temp.macosx-10.9-x86_64-3.7/src/wrapper.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/hmishfaq/miniconda3/envs/rlberry/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/setup.py'"'"'; __file__='"'"'/private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-install-c4eb4muq/pyopengl-accelerate_e9ab1b03c35f4124afb92343fb341d15/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hx/pgz_r8ps30n36q4qds34t0340000gn/T/pip-record-6eze1xi4/install-record.txt --single-version-externally-managed --compile --install-headers /Users/hmishfaq/miniconda3/envs/rlberry/include/python3.7m/PyOpenGL-accelerate Check the logs for full command output.`

**Comment by yfletberliac** [comment] 2021-03-15 18:24
Hi,

I cannot reproduce your error. Could you please specify your:
        -   OS
	-   Python version
	-   gcc version
please?

**Comment by hmishfaq** [comment] 2021-03-15 18:52
OS- macOS Catalina 10.15.7 
Python version 3.7.10
gcc 10.2.0

**Comment by hmishfaq** [comment] 2021-03-15 18:54
It worked after reinstalling gcc. Thanks!

**Comment by yfletberliac** [comment] 2021-03-15 18:55
Great! Closing :)

**Closed by yfletberliac** 2021-03-15 18:55 UTC

**Comment by omardrwch** [comment] 2021-03-15 19:17
By the way, the rendering of the environments using `PyOpenGL` also seem to work **without** `PyOpenGL-accelerate`!
